
ARGS:
 tab: 'V1_hrnet_pw3d_ft'
 dataset: 'pw3d'
 gpu: 0,1
 distributed_training: False
 model_version: 1
 epoch: 200
 start_epoch: 1

 master_batch_size: -1
 val_batch_size: 64
 batch_size: 64
 nw: 6
 nw_eval: 2
 lr: 0.00005
 adjust_lr_factor: 0.2

 fine_tune: True
 fix_backbone_training_scratch: False
 match_preds_to_gts_for_supervision: True
 eval: False
 supervise_global_rot: False
 calc_PVE_error: False

 model_return_loss: True
 collision_aware_centermap: True
 collision_factor: 0.2
 homogenize_pose_space: False
 shuffle_crop_mode: False
 shuffle_crop_ratio_2d: 0.1
 shuffle_crop_ratio_3d: 0.2

 merge_smpl_camera_head: False
 head_block_num: 2

 backbone: 'hrnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2

 model_path: /home/dev2/Drive_C/MK/IdHMR/Ab02/checkpoints/hrnet_cm64_V1_hrnet_pw3d_ft_on_gpu0,1_val/hrnet_cm64_V1_hrnet_pw3d_ft_epoch_0.pkl

loss_weight:
  MPJPE: 200.
  PAMPJPE: 360.
  P_KP2D: 400.
  Pose: 80.
  Shape: 6.
  Prior: 1.6
  CenterMap: 160.
  Cam: 200.
  JointMap: 50.
  CenterID: 50.
  JointID: 50.


sample_prob:
 # crowdpose: 0.2
 # pw3d: 0.8
 pw3d: 1.0